# Tasks

- [x] Project Initialization <!-- id: 0 -->
    - [x] Create project structure (frontend/backend) <!-- id: 1 -->
    - [x] Initialize Astro frontend <!-- id: 2 -->
    - [x] Initialize Express backend <!-- id: 3 -->
- [x] Frontend Development <!-- id: 4 -->
    - [x] Setup Design System (CSS Variables, Typography) <!-- id: 5 -->
    - [x] Build Landing Page <!-- id: 6 -->
    - [x] Build Dashboard Layout <!-- id: 7 -->
    - [x] Implement Job Matching View (Mock) <!-- id: 8 -->
    - [x] Build Resumes Page <!-- id: 15 -->
    - [x] Build Applications Page <!-- id: 16 -->
- [x] Backend Development <!-- id: 9 -->
    - [x] Setup Express Server <!-- id: 10 -->
    - [x] Create basic API endpoints <!-- id: 11 -->
    - [x] Setup Prisma + SQLite (for local dev, MySQL later) <!-- id: 12 -->
- [/] Integration <!-- id: 13 -->
    - [x] Connect Frontend to Backend <!-- id: 14 -->
    - [/] Configure for Deployment <!-- id: 17 -->
        - [/] Update Frontend API URL <!-- id: 18 -->
        - [ ] Configure Backend Static Serving <!-- id: 19 -->
        - [ ] Create Build Scripts <!-- id: 20 -->
